"use strict";
exports.__esModule = true;
require('dotenv').config();
var command_1 = require("./command");
var Telegraf = require('telegraf');
var bot = new Telegraf(process.env.BOT_TOKEN);
bot.start(function (ctx) { return ctx.reply('Welcome on telegramDeFi'); });
bot.help(function (ctx) { return ctx.reply('telegramDeFi - V0.1'); });
bot.command('getNewWallet', function (ctx) { return ctx.reply(command_1.getNewWallet(ctx.from.id)); });
bot.command('getBalance', function (ctx) { return ctx.reply(command_1.getBalance(ctx.from.id)); });
bot.command('getAddress', function (ctx) { return ctx.reply(command_1.getNewWallet(ctx.from.id)); });
bot.command('getQRcode', function (ctx) { return ctx.reply(command_1.getQRcode(ctx.from.id)); });
bot.launch();
